@php
    $logo = \App\Models\Setting::logo();
    $clinicName = \App\Models\Setting::get('clinic_name', config('app.name'));
@endphp
<div class="ledger-sheet">
    <div class="ledger-head">
        <div class="brand">
            <div class="mark">
                @if ($logo)<img src="{{ asset('storage/' . $logo) }}">@else <i class="fas fa-tooth"></i>@endif
            </div>
            <div class="name">{{ $clinicName }}</div>
        </div>
        <div class="title">
            <h2>PATIENT LEDGER</h2>
            <small>Generated on: {{ now()->format('d M Y H:i') }}</small>
        </div>
    </div>

    <div class="ledger-info-bar">
        <div><div class="label">Name</div><div class="value">{{ $patient->full_name }}</div></div>
        <div><div class="label">ID</div><div class="value">{{ $patient->patient_code }}</div></div>
        <div><div class="label">Phone</div><div class="value">{{ $patient->phone ?? '-' }}</div></div>
        <div class="balance"><div class="label">Current Balance</div><div class="value">${{ number_format($transactions->last()['balance'] ?? 0, 2) }}</div></div>
    </div>

    <div class="ledger-section-title"><span class="bar"></span> Transaction History</div>
    <div style="overflow-x:auto;">
        <table class="ledger-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th class="num">Amount Due</th>
                    <th class="num">Amount Paid</th>
                    <th class="num">Balance</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($transactions as $t)
                    <tr>
                        <td>{{ $t['date']->format('d M Y') }}</td>
                        <td>{{ $t['description'] }}</td>
                        <td class="num due-amt">{{ $t['due'] ? '$' . number_format($t['due'], 2) : '' }}</td>
                        <td class="num paid-amt">{{ $t['paid'] ? '$' . number_format($t['paid'], 2) : '' }}</td>
                        <td class="num">${{ number_format($t['balance'], 2) }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" style="text-align:center;color:var(--text-soft);padding:2rem;">No transactions recorded yet.</td></tr>
                @endforelse
            </tbody>
            @if ($transactions->isNotEmpty())
            <tfoot>
                <tr>
                    <td colspan="2">TOTALS</td>
                    <td class="num">${{ number_format($totalDue, 2) }}</td>
                    <td class="num">${{ number_format($totalPaid, 2) }}</td>
                    <td class="num">${{ number_format($transactions->last()['balance'], 2) }}</td>
                </tr>
            </tfoot>
            @endif
        </table>
    </div>

    <p class="ledger-foot-note">This statement was generated by {{ $clinicName }}.</p>
</div>
