<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>@yield('report-title')</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 14px; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .header img { height: 60px; margin-bottom: 6px; }
        .header h2 { margin: 0; color: #4f46e5; }
        .header h3 { margin: 4px 0 0; }
        .meta { width: 100%; margin-bottom: 12px; font-size: 10px; color: #555; }
        .meta td { padding: 2px 0; }
        table.data { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        table.data th, table.data td { border: 1px solid #ddd; padding: 5px 7px; text-align: left; }
        table.data th { background: #f4f4f7; }
        .text-end { text-align: right; }
        .kpis { width: 100%; margin-bottom: 14px; }
        .kpis td { width: 25%; text-align: center; border: 1px solid #eee; padding: 8px; }
        .kpis .value { font-size: 16px; font-weight: bold; color: #4f46e5; display: block; }
        .kpis .label { font-size: 9px; color: #777; }
        .footer { margin-top: 20px; text-align: center; color: #999; font-size: 9px; border-top: 1px solid #eee; padding-top: 6px; }
        .section-title { font-size: 12px; font-weight: bold; margin: 10px 0 6px; color: #333; }
    </style>
</head>
<body>
    <div class="header">
        @php $logo = \App\Models\Setting::get('clinic_logo'); @endphp
        @if ($logo)
            <img src="{{ public_path('storage/' . $logo) }}" alt="Logo">
        @endif
        <h2>{{ \App\Models\Setting::get('clinic_name', config('app.name')) }}</h2>
        <h3>@yield('report-title')</h3>
    </div>

    <table class="meta">
        <tr>
            <td><strong>Date Generated:</strong> {{ now()->format('M j, Y H:i') }}</td>
            <td class="text-end"><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
        </tr>
        <tr>
            <td colspan="2"><strong>Filter Summary:</strong> {{ \App\Support\Reports\DateRangeResolver::formatRange($range['from'], $range['to']) }}
                @foreach (($filters ?? []) as $key => $value)
                    @continue(blank($value))
                    &middot; {{ \Illuminate\Support\Str::headline($key) }}: {{ $value }}
                @endforeach
            </td>
        </tr>
    </table>

    @yield('report-content')

    <p class="footer">Confidential &mdash; Dental Clinic Management System</p>
</body>
</html>
